// import { PrismaClient } from "@prisma/client";
// const prisma = new PrismaClient();

// const users = [
//   { name: "Giles Lebsack", email: "Dan.Blanda@Lavonne.ca" },
//   { name: "Terrence Kutch", email: "Harris_Simone@Nya.co.uk" },
//   { name: "Noe Parisian", email: "Marilie_Wilderman@Lemke.me" },
//   { name: "Damien Gorczany", email: "Dejuan_Upton@Elna.name" },
//   { name: "Monty Sanford", email: "Samantha_Pacocha@gmail.com" },
//   { name: "Maddison Howe", email: "Burley.Rogahn@gmail.com" },
//   // { name: "Jean Rath", email: "Hamill_Ebony@Treutel.name" },
//   // { name: "Damon Koepp", email: "Graham.Keebler@yahoo.com" },
//   // { name: "Maude Murray", email: "Zane.Olson@yahoo.com" },
//   // { name: "Destany Hickle", email: "Keshaun.Weissnat@Anabel.biz" },
//   // { name: "Beryl Price", email: "Issac_Will@hotmail.com" },
//   // { name: "Precious Koch", email: "Michaela.Legros@hotmail.com" },
//   // { name: "Diamond Price", email: "Shane_Thompson@Moen.biz" },
//   // { name: "Bailey Willms", email: "Sedrick.Ruecker@yahoo.com" },
//   // { name: "Bettie Kris", email: "Maxwell_Cremin@Deven.co.uk" },
//   // { name: "Greg Abbott", email: "Green_Mariam@yahoo.com" },
//   // { name: "Jermaine Jerde", email: "Reginald_Wolff@gmail.com" },
//   // { name: "Vicky Turcotte", email: "Lauriane_Kihn@Mathias.org" },
//   // { name: "Chaim Luettgen", email: "Savion_Konopelski@yahoo.com" },
//   // { name: "Wendy White", email: "Predovic_Alysson@yahoo.com" },
//   // { name: "Rocio White", email: "Olga.Pacocha@Bailey.io" },
//   // { name: "Keith Wuckert", email: "Audra.Goyette@hotmail.com" },
//   // { name: "Jaden Nicolas", email: "Bell_Waelchi@Aric.net" },
//   // { name: "Euna Dare", email: "Elwin_Smitham@Otilia.name" },
//   // { name: "Raheem Collins", email: "Tracey_Hermiston@yahoo.com" },
//   // { name: "Alexys Shanahan", email: "Evie.Schoen@Krista.biz" },
//   // { name: "Erica Walter", email: "Howell.Rita@yahoo.com" },
//   // { name: "Jazlyn Gislason", email: "Autumn.Runolfsson@Olen.biz" },
//   // { name: "Nella Swaniawski", email: "Bosco_Arch@Don.net" },
//   // { name: "Kaylin Parisian", email: "Melyssa_Olson@yahoo.com" },
//   // { name: "Osborne Mayer", email: "Ferry.Fae@gmail.com" },
//   // { name: "Brian Parker", email: "Corene.Tremblay@yahoo.com" },
//   // { name: "Darien Herzog", email: "Kennith_Stiedemann@Josie.com" },
//   // { name: "Burnice Schmeler", email: "Emerson_Cremin@Cronin.co.uk" },
//   // { name: "Dariana Cummerata", email: "Kennedi.Kuhn@yahoo.com" },
//   // { name: "Yasmine Ebert", email: "Huels_Wyman@gmail.com" },
//   // { name: "Philip Friesen", email: "Brekke.Geoffrey@Vincenza.ca" },
//   // { name: "Jazmyn Hackett", email: "Towne_Talon@yahoo.com" },
//   // { name: "Jonathon Kerluke", email: "Abernathy.Cristina@yahoo.com" },
//   // { name: "Hildegard Fritsch", email: "Merritt.Ward@gmail.com" },
//   // { name: "Brenna Murphy", email: "Oceane.Ward@Howe.co.uk" },
//   // { name: "Kamren Schroeder", email: "Norwood_Hackett@Raynor.com" },
//   // { name: "Micaela Nader", email: "McClure_Santiago@yahoo.com" },
//   // { name: "Aileen Douglas", email: "Hubert.Reichel@gmail.com" },
//   // { name: "Myra Fadel", email: "Lubowitz.Jazmin@Connelly.biz" },
//   // { name: "Jabari Hartmann", email: "Ora.Schuster@gmail.com" },
//   // { name: "Lane Zemlak", email: "Destiney.Jacobson@yahoo.com" },
//   // { name: "Eloisa Gleason", email: "Doyle_Seamus@Weber.us" },
//   // { name: "Anastasia Rohan", email: "Korbin_Tillman@gmail.com" },
//   // { name: "Ross Dooley", email: "Sadye_Boyer@Bradly.net" },
//   // { name: "Odessa Christiansen", email: "Willms_Silas@hotmail.com" },
//   // { name: "Carter Stracke", email: "Destany.Hartmann@yahoo.com" },
//   // { name: "Robyn Kling", email: "Sporer_Sandrine@Bayer.net" },
//   // { name: "Destiney Runte", email: "Kunde.Eliza@gmail.com" },
//   // { name: "Concepcion Friesen", email: "Carley.DuBuque@yahoo.com" },
//   // { name: "Corene Bartell", email: "Wolff.Brianne@Cordie.me" },
//   // { name: "Xander Kilback", email: "Runolfsson_Boris@hotmail.com" },
//   // { name: "Luigi Smith", email: "Linnea.Morissette@Melissa.name" },
//   // { name: "Jazmin Will", email: "Cassin_Emerald@Krajcik.org" },
//   // { name: "Laverne Jacobi", email: "Kale.Beahan@Graciela.ca" },
//   // { name: "Pedro Sauer", email: "Ethan_Kohler@gmail.com" },
//   // { name: "Emily Treutel", email: "Jace.Anderson@gmail.com" },
//   // { name: "Anjali Thompson", email: "Morar_Bianka@Rey.biz" },
//   // { name: "Emmy Romaguera", email: "Leonie.Schroeder@yahoo.com" },
//   // { name: "Nya Thiel", email: "Mayert.Yessenia@hotmail.com" },
//   // { name: "Caleigh Barton", email: "Abner_Runte@hotmail.com" },
//   // { name: "Hailie Swaniawski", email: "Josefa_Brekke@yahoo.com" },
//   // { name: "Jamie Balistreri", email: "Nils_Connelly@yahoo.com" },
//   // { name: "Janie Hickle", email: "Oberbrunner_Shaylee@Ramona.me" },
//   // { name: "Jalen Haag", email: "Jacobi_Mazie@hotmail.com" },
//   // { name: "Constantin Ondricka", email: "Lucy.Bednar@Ariane.ca" },
//   // { name: "Roger Hilpert", email: "Damaris.Becker@hotmail.com" },
//   // { name: "Judd Zemlak", email: "Trudie.Bogisich@Perry.io" },
//   // { name: "Leatha Wiza", email: "Providenci_Trantow@yahoo.com" },
//   // { name: "Thurman Wisoky", email: "McDermott_Ronny@yahoo.com" },
//   // { name: "Fredrick Hills", email: "Dovie_Russel@hotmail.com" },
//   // { name: "Jordyn Crooks", email: "Savion.Balistreri@Beahan.org" },
//   // { name: "Reginald Lesch", email: "Katheryn_Mitchell@Bashirian.us" },
//   // { name: "Cleora Paucek", email: "Cole.Irwin@yahoo.com" },
//   // { name: "Favian Wolff", email: "Abshire_Dandre@yahoo.com" },
//   // { name: "Jamar Bode", email: "Thea.Halvorson@Donato.co.uk" },
//   // { name: "River Cremin", email: "Friesen_Jayden@Viviane.name" },
//   // { name: "Chaya Watsica", email: "Chadrick_Batz@yahoo.com" },
//   // { name: "Cielo Reichel", email: "Alessia.Greenfelder@Medhurst.org" },
//   // { name: "Samara Hegmann", email: "Will_Heather@Ruecker.info" },
//   // { name: "Zelma Buckridge", email: "Autumn.Howe@Mayer.ca" },
//   // { name: "Noe Lemke", email: "Windler_Giovani@gmail.com" },
//   // { name: "Rhiannon Williamson", email: "Dickens.Skye@Boehm.ca" },
//   // { name: "Clemmie VonRueden", email: "Orlando.Weissnat@hotmail.com" },
//   // { name: "Emmy Raynor", email: "Adell.Mann@Theo.tv" },
//   // { name: "Bernardo Schneider", email: "Jasen_Schaden@Schinner.info" },
//   // { name: "Carlie Fritsch", email: "Eliane_Powlowski@Kaleigh.com" },
//   // { name: "Tod Balistreri", email: "Dejon_Jast@gmail.com" },
//   // { name: "Damien Connelly", email: "Henriette_Hettinger@Kathryn.biz" },
//   // { name: "Dolores Lubowitz", email: "Lamar_Heidenreich@Teagan.io" },
//   // { name: "Barton Berge", email: "Roberto_Kertzmann@Fay.info" },
//   // { name: "Josue Ratke", email: "Kylee_Fahey@Letitia.com" },
//   // { name: "Mohamed Wisozk", email: "Armand.Willms@yahoo.com" },
//   // { name: "Jaycee Feeney", email: "Jeanette_Legros@gmail.com" },
//   // { name: "Edmund Upton", email: "Dora.Mitchell@Collin.biz" },
// ];

// async function createDmmUsers() {
//   for (let user of users) {
//     const _user = await prisma.user.create({
//       data: {
//         name: user.name,
//         email: user.email,
//       },
//     });
//     console.log(_user);
//   }
// }
// createDmmUsers();
